version: '3.8'
services:
  db:
    image: kartoza/postgis:17-3.5
    container_name: osm_db
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gisuser
      - POSTGRES_PASS=gispassword
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_HOST_AUTH_METHOD=trust # <--- Dòng này ép DB tin tưởng kết nối local
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
