spring.application.name=gis-demo

# URL kết nối đến database trong Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/gis

# Thông tin đăng nhập
spring.datasource.username=gisuser
spring.datasource.password=gispassword

# Driver điều khiển
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Thiết lập log
logging.file.name=logs/gis-demo.log
logging.level.root=INFO
logging.level.gis.gis_demo=DEBUG

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
