spring.application.name=gis-demo

# URL kết nối đến database trong Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/gis

# Thông tin đăng nhập
spring.datasource.username=gisuser
spring.datasource.password=gispassword

# Driver điều khiển
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate (Tự động cập nhật bảng dựa trên Code Java)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
